import { FaCode } from "react-icons/fa";
import {
  SiHtml5,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiVite,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPython,
  SiC,
  SiGit,
  SiGithub,
  SiPostman,
  SiVercel,
  SiNetlify,
  SiRender,
  SiRailway,
  SiFirebase,
  SiJsonwebtokens,
  SiTensorflow,
  SiOpencv,
  SiStreamlit,
  SiFigma,
  SiRedux,
  SiZod,
  SiFramer,
  SiCss,
  SiCanvas,
} from "react-icons/si";

export const techIcons = {
  HTML: SiHtml5,
  HTML5: SiHtml5,
  CSS: SiCss,
  CSS3: SiCss,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  React: SiReact,
  "React.js": SiReact,
  Vite: SiVite,
  "Tailwind CSS": SiTailwindcss,
  "Node.js": SiNodedotjs,
  Node: SiNodedotjs,
  Express: SiExpress,
  "Express.js": SiExpress,
  MongoDB: SiMongodb,
  Python: SiPython,
  C: SiC,
  Git: SiGit,
  GitHub: SiGithub,
  Postman: SiPostman,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  Render: SiRender,
  Railway: SiRailway,
  Firebase: SiFirebase,
  JWT: SiJsonwebtokens,
  TensorFlow: SiTensorflow,
  "TensorFlow/Keras": SiTensorflow,
  OpenCV: SiOpencv,
  Streamlit: SiStreamlit,
  Figma: SiFigma,
  Canva: SiCanvas,
  Redux: SiRedux,
  Zustand: SiRedux,
  Zod: SiZod,
  "Framer Motion": SiFramer,
  "Git & GitHub": SiGit,
  "REST APIs": FaCode,
  "JWT Authentication": SiJsonwebtokens,
};

export const getTechIcon = (name) => {
  if (!name) return FaCode;
  return techIcons[name] || techIcons[String(name).trim()] || FaCode;
};
